export const FILTER_OPTIONS = {
  gender: [
    { label: "Women", value: "female" },
    { label: "Men", value: "male" },
    { label: "Unisex", value: "unisex" },
  ],

  category: [
    { label: "Tops", value: "tops" },
    { label: "Bottoms", value: "bottoms" },
    { label: "Dresses", value: "dresses" },
    { label: "Outerwear", value: "outerwear" },
    { label: "Shoes", value: "shoes" },
    { label: "Accessories", value: "accessories" },
    { label: "Activewear", value: "activewear" },
    { label: "Swimwear", value: "swimwear" },
    { label: "Loungewear", value: "loungewear" },
  ],

  size: [
    { label: "XXS", value: "xxs" },
    { label: "XS", value: "xs" },
    { label: "S", value: "s" },
    { label: "M", value: "m" },
    { label: "L", value: "l" },
    { label: "XL", value: "xl" },
    { label: "XXL", value: "xxl" },
    { label: "0", value: "0" },
    { label: "2", value: "2" },
    { label: "4", value: "4" },
    { label: "6", value: "6" },
    { label: "8", value: "8" },
    { label: "10", value: "10" },
    { label: "12", value: "12" },
    { label: "14", value: "14" },
    { label: "16", value: "16" },
  ],

  color: [
    { label: "Black", value: "black", hex: "#000000" },
    { label: "White", value: "white", hex: "#FFFFFF" },
    { label: "Gray", value: "gray", hex: "#808080" },
    { label: "Beige", value: "beige", hex: "#D6C7B0" },
    { label: "Brown", value: "brown", hex: "#7B4B2A" },
    { label: "Blue", value: "blue", hex: "#1D4ED8" },
    { label: "Navy", value: "navy", hex: "#1E3A8A" },
    { label: "Green", value: "green", hex: "#15803D" },
    { label: "Olive", value: "olive", hex: "#556B2F" },
    { label: "Yellow", value: "yellow", hex: "#EAB308" },
    { label: "Orange", value: "orange", hex: "#F97316" },
    { label: "Red", value: "red", hex: "#DC2626" },
    { label: "Pink", value: "pink", hex: "#EC4899" },
    { label: "Purple", value: "purple", hex: "#7C3AED" },
    { label: "Gold", value: "gold", hex: "#D4AF37" },
    { label: "Silver", value: "silver", hex: "#C0C0C0" },
    {
      label: "Multi",
      value: "multi",
      hex: "linear-gradient(135deg, red, orange, yellow, green, blue, purple)",
    },
  ],

  availability: [
    { label: "In stock", value: "in_stock" },
    { label: "Out of stock", value: "out_of_stock" },
    { label: "Unknown", value: "unknown" },
  ],

  store: [
    { label: "ASOS", value: "ASOS" },
    { label: "Amazon", value: "Amazon" },
    { label: "Depop", value: "Depop" },
    { label: "Unknown", value: "Unknown" },
  ],

  brand: [
    { label: "Zara", value: "Zara" },
    { label: "Aritzia", value: "Aritzia" },
    { label: "Reformation", value: "Reformation" },
    { label: "COS", value: "COS" },
  ],
};

export const DEFAULT_FILTERS = {
  gender: [],
  category: [],
  size: [],
  color: [],
  brand: [],
  store: [],
  availability: [],
  priceMin: "",
  priceMax: "",
};

export const CATEGORY_KEYWORDS = {
  outerwear: [
    "jacket",
    "coat",
    "blazer",
    "parka",
    "trench",
    "puffer",
    "bomber",
    "windbreaker",
  ],
  tops: [
    "top",
    "shirt",
    "t-shirt",
    "tee",
    "blouse",
    "tank",
    "camisole",
    "sweater",
    "hoodie",
    "cardigan",
    "knit",
    "polo",
  ],
  bottoms: [
    "jeans",
    "pants",
    "trousers",
    "leggings",
    "joggers",
    "shorts",
    "skirt",
  ],
  dresses: ["dress", "gown", "maxi dress", "mini dress", "midi dress"],
  shoes: [
    "shoe",
    "sneaker",
    "boot",
    "heel",
    "loafer",
    "sandal",
    "trainer",
    "slipper",
  ],
  accessories: [
    "bag",
    "purse",
    "belt",
    "hat",
    "cap",
    "scarf",
    "jewelry",
    "necklace",
    "earrings",
    "bracelet",
    "watch",
    "sunglasses",
  ],
  activewear: [
    "legging",
    "sports bra",
    "track pants",
    "running",
    "gym",
    "activewear",
    "workout",
  ],
  swimwear: [
    "swimsuit",
    "bikini",
    "one-piece",
    "swim",
    "trunks",
    "boardshorts",
  ],
  loungewear: [
    "loungewear",
    "pajama",
    "robe",
    "sweatpants",
    "sweatshirt",
    "sleepwear",
  ],
};

export const COLOR_KEYWORDS = {
  black: ["black", "jet black", "charcoal black"],
  white: ["white", "ivory", "off-white", "cream"],
  gray: ["gray", "grey", "charcoal", "heather gray"],
  beige: ["beige", "tan", "sand", "camel", "stone", "nude"],
  brown: ["brown", "chocolate", "mocha", "espresso", "taupe"],
  blue: ["blue", "cobalt", "sky blue", "baby blue", "royal blue"],
  navy: ["navy", "midnight navy"],
  green: ["green", "emerald", "mint", "sage", "forest"],
  olive: ["olive", "khaki", "army green"],
  yellow: ["yellow", "mustard"],
  orange: ["orange", "rust", "terracotta", "burnt orange"],
  red: ["red", "crimson", "burgundy", "maroon", "wine"],
  pink: ["pink", "rose", "blush", "fuchsia", "hot pink"],
  purple: ["purple", "lavender", "lilac", "violet", "plum"],
  gold: ["gold"],
  silver: ["silver"],
  multi: ["multi", "multicolor", "rainbow", "printed", "patterned"],
};

export const GENDER_KEYWORDS = {
  female: ["women", "woman", "womens", "female", "ladies", "girl", "girls"],
  male: ["men", "man", "mens", "male", "boys", "boy"],
  unisex: ["unisex"],
};
