module.exports = {
  black: ['black', 'jet black', 'charcoal black'],
  white: ['white', 'ivory', 'off-white', 'cream'],
  gray: ['gray', 'grey', 'charcoal', 'heather gray'],
  beige: ['beige', 'tan', 'sand', 'camel', 'stone', 'nude'],
  brown: ['brown', 'chocolate', 'mocha', 'espresso', 'taupe'],
  blue: ['blue', 'cobalt', 'sky blue', 'baby blue', 'royal blue'],
  navy: ['navy', 'midnight navy'],
  green: ['green', 'emerald', 'mint', 'sage', 'forest'],
  olive: ['olive', 'khaki', 'army green'],
  yellow: ['yellow', 'mustard'],
  orange: ['orange', 'rust', 'terracotta', 'burnt orange'],
  red: ['red', 'crimson', 'burgundy', 'maroon', 'wine'],
  pink: ['pink', 'rose', 'blush', 'fuchsia', 'hot pink'],
  purple: ['purple', 'lavender', 'lilac', 'violet', 'plum'],
  gold: ['gold'],
  silver: ['silver'],
  multi: ['multi', 'multicolor', 'rainbow', 'printed', 'patterned'],
};
